CREATE TABLE IF NOT EXISTS user_notification_state (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    security_notifications_seen_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT '1970-01-01 00:00:00+00',
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
